<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference
      Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="10.0.0"
    />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="Vernou.Swashbuckle.HttpResultsAdapter" Version="1.0.3" />
  </ItemGroup>
</Project>
