name: "Setup .NET"
description: "Sets up the .NET SDK using the version defined in global.json and caching of nuget packages"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v5
      with:
        global-json-file: "global.json"
        cache: true
        cache-dependency-path: "**/packages.lock.json"
